// P23 (OP-222) `a2a completion`: render a static shell-completion script for
// bash / zsh / fish. This file holds the pure renderer — no IO, no flags — so
// it is exhaustively unit-testable and deterministic. The command wrapper +
// flag/exit handling lives in cmd_completion.go; the verb inventory (the list
// of top-level commands and `contract` sub-verbs) is INJECTED by cmd/a2a,
// which is the only place that knows buildCommands() — internal/cli never
// enumerates the dispatch surface itself.
//
// Names-only by design (no per-command descriptions, no dynamic __complete
// callback): the drift surface is exactly the set of command NAMES, which the
// name-parity guards (catalog_test.go / a sibling completion parity test)
// already keep honest. Richer, context-aware completion is a documented V2.
package cli

import (
	"fmt"
	"sort"
	"strings"
)

// CompletionShells is the set of shells `a2a completion` can render, in the
// order shown in usage.
var CompletionShells = []string{"bash", "zsh", "fish"}

// subFamily is one `a2a <verb> <sub>` sub-verb family (e.g. contract, feedback)
// resolved to its sorted sub-verb names. RenderCompletion emits one
// prev-verb-gated branch per family, so completion generalizes to N families
// without a per-family code edit (contract + feedback today; the pattern
// recurs). Families are rendered in sorted order for deterministic output.
type subFamily struct {
	verb string
	subs []string
}

// RenderCompletion returns the completion script for shell, listing cmds as the
// top-level verbs and each entry of subFamilies as a `a2a <verb> <sub>` family.
// cmds, the family list, and every family's subs are copied and sorted so the
// output is deterministic regardless of the caller's ordering. An unknown shell
// is an error (never a silent empty script).
func RenderCompletion(shell string, cmds []string, subFamilies map[string][]string) (string, error) {
	c := append([]string(nil), cmds...)
	sort.Strings(c)

	fams := make([]subFamily, 0, len(subFamilies))
	for verb, subs := range subFamilies {
		s := append([]string(nil), subs...)
		sort.Strings(s)
		fams = append(fams, subFamily{verb: verb, subs: s})
	}
	sort.Slice(fams, func(i, j int) bool { return fams[i].verb < fams[j].verb })

	switch shell {
	case "bash":
		return renderBash(c, fams), nil
	case "zsh":
		return renderZsh(c, fams), nil
	case "fish":
		return renderFish(c, fams), nil
	default:
		return "", fmt.Errorf("unknown shell %q (supported: %s)", shell, strings.Join(CompletionShells, ", "))
	}
}

// renderBash emits a self-contained bash function. It uses only COMP_WORDS /
// COMP_CWORD / compgen — no bash-completion framework — so `source <(a2a
// completion bash)` works even on stock macOS bash 3.2; the framework is only
// needed to AUTO-load the drop-in file, not for the script to function.
func renderBash(cmds []string, fams []subFamily) string {
	var b strings.Builder
	b.WriteString("# a2a bash completion. Generated by `a2a completion bash`.\n")
	b.WriteString("# Load now:   source <(a2a completion bash)\n")
	b.WriteString("# Persist:    a2a completion bash > \"${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/a2a\"\n")
	b.WriteString("_a2a() {\n")
	b.WriteString("    local cur prev\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	fmt.Fprintf(&b, "    local commands=%q\n", strings.Join(cmds, " "))
	for _, f := range fams {
		fmt.Fprintf(&b, "    if [ \"$prev\" = %q ]; then\n", f.verb)
		fmt.Fprintf(&b, "        COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(f.subs, " "))
		b.WriteString("        return 0\n")
		b.WriteString("    fi\n")
	}
	b.WriteString("    if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n")
	b.WriteString("    fi\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _a2a a2a\n")
	return b.String()
}

// renderZsh emits an autoload-style `#compdef` body: when compinit autoloads a
// file named `_a2a` from a directory on $fpath, zsh executes the file body as
// the completion function, so the body uses `words`/`CURRENT`/`compadd`
// directly (no wrapper function). This matches where install.sh writes it.
func renderZsh(cmds []string, fams []subFamily) string {
	var b strings.Builder
	b.WriteString("#compdef a2a\n")
	b.WriteString("# a2a zsh completion. Generated by `a2a completion zsh`.\n")
	b.WriteString("# Install: save as `_a2a` in a directory on your $fpath, then reload:\n")
	b.WriteString("#   fpath=(~/.zsh/completions $fpath)\n")
	b.WriteString("#   autoload -Uz compinit && compinit\n")
	fmt.Fprintf(&b, "local -a _a2a_cmds\n")
	fmt.Fprintf(&b, "_a2a_cmds=(%s)\n", zshWords(cmds))
	for _, f := range fams {
		fmt.Fprintf(&b, "local -a _a2a_%s\n", f.verb)
		fmt.Fprintf(&b, "_a2a_%s=(%s)\n", f.verb, zshWords(f.subs))
	}
	b.WriteString("if (( CURRENT == 2 )); then\n")
	b.WriteString("    compadd -a _a2a_cmds\n")
	b.WriteString("    return\n")
	b.WriteString("fi\n")
	for _, f := range fams {
		fmt.Fprintf(&b, "if (( CURRENT == 3 )) && [[ \"${words[2]}\" == %q ]]; then\n", f.verb)
		fmt.Fprintf(&b, "    compadd -a _a2a_%s\n", f.verb)
		b.WriteString("    return\n")
		b.WriteString("fi\n")
	}
	return b.String()
}

// renderFish emits one `complete` line per verb. Top-level verbs are offered
// only when no subcommand has been typed yet (__fish_use_subcommand); the
// contract sub-verbs only after `contract` (__fish_seen_subcommand_from). `-f`
// disables file completion, which a2a's verbs never take as their first token.
func renderFish(cmds []string, fams []subFamily) string {
	var b strings.Builder
	b.WriteString("# a2a fish completion. Generated by `a2a completion fish`.\n")
	b.WriteString("# Install: a2a completion fish > ~/.config/fish/completions/a2a.fish\n")
	b.WriteString("complete -c a2a -f\n")
	for _, cmd := range cmds {
		fmt.Fprintf(&b, "complete -c a2a -n __fish_use_subcommand -a %s\n", cmd)
	}
	for _, f := range fams {
		for _, sub := range f.subs {
			fmt.Fprintf(&b, "complete -c a2a -n '__fish_seen_subcommand_from %s' -a %s\n", f.verb, sub)
		}
	}
	return b.String()
}

// zshWords joins verb names for a zsh array literal. The names are a fixed,
// validated vocabulary (buildCommands keys / contract sub-verbs) — plain
// tokens with no shell metacharacters — so they need no quoting; a space
// separator is the zsh array literal form.
func zshWords(names []string) string {
	return strings.Join(names, " ")
}
