// P23 (OP-222) `a2a completion`: render a static shell-completion script for
// bash / zsh / fish. This file holds the pure renderer — no IO, no flags — so
// it is exhaustively unit-testable and deterministic. The command wrapper +
// flag/exit handling lives in cmd_completion.go; the verb inventory (the list
// of top-level commands and `contract` sub-verbs) is INJECTED by cmd/a2a,
// which is the only place that knows buildCommands() — internal/cli never
// enumerates the dispatch surface itself.
//
// Names-only by design (no per-command descriptions, no dynamic __complete
// callback): the drift surface is exactly the set of command NAMES, which the
// name-parity guards (catalog_test.go / a sibling completion parity test)
// already keep honest. Richer, context-aware completion is a documented V2.
package cli

import (
	"fmt"
	"sort"
	"strings"
)

// CompletionShells is the set of shells `a2a completion` can render, in the
// order shown in usage.
var CompletionShells = []string{"bash", "zsh", "fish"}

// RenderCompletion returns the completion script for shell, listing cmds as the
// top-level verbs and contractSubs as the `a2a contract <sub>` sub-verbs. Both
// slices are copied and sorted so the output is deterministic regardless of the
// caller's ordering. An unknown shell is an error (never a silent empty script).
func RenderCompletion(shell string, cmds, contractSubs []string) (string, error) {
	c := append([]string(nil), cmds...)
	sort.Strings(c)
	subs := append([]string(nil), contractSubs...)
	sort.Strings(subs)

	switch shell {
	case "bash":
		return renderBash(c, subs), nil
	case "zsh":
		return renderZsh(c, subs), nil
	case "fish":
		return renderFish(c, subs), nil
	default:
		return "", fmt.Errorf("unknown shell %q (supported: %s)", shell, strings.Join(CompletionShells, ", "))
	}
}

// renderBash emits a self-contained bash function. It uses only COMP_WORDS /
// COMP_CWORD / compgen — no bash-completion framework — so `source <(a2a
// completion bash)` works even on stock macOS bash 3.2; the framework is only
// needed to AUTO-load the drop-in file, not for the script to function.
func renderBash(cmds, subs []string) string {
	var b strings.Builder
	b.WriteString("# a2a bash completion. Generated by `a2a completion bash`.\n")
	b.WriteString("# Load now:   source <(a2a completion bash)\n")
	b.WriteString("# Persist:    a2a completion bash > \"${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/a2a\"\n")
	b.WriteString("_a2a() {\n")
	b.WriteString("    local cur prev\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	fmt.Fprintf(&b, "    local commands=%q\n", strings.Join(cmds, " "))
	fmt.Fprintf(&b, "    local contract_subs=%q\n", strings.Join(subs, " "))
	b.WriteString("    if [ \"$prev\" = \"contract\" ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$contract_subs\" -- \"$cur\") )\n")
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n")
	b.WriteString("    if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n")
	b.WriteString("    fi\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _a2a a2a\n")
	return b.String()
}

// renderZsh emits an autoload-style `#compdef` body: when compinit autoloads a
// file named `_a2a` from a directory on $fpath, zsh executes the file body as
// the completion function, so the body uses `words`/`CURRENT`/`compadd`
// directly (no wrapper function). This matches where install.sh writes it.
func renderZsh(cmds, subs []string) string {
	var b strings.Builder
	b.WriteString("#compdef a2a\n")
	b.WriteString("# a2a zsh completion. Generated by `a2a completion zsh`.\n")
	b.WriteString("# Install: save as `_a2a` in a directory on your $fpath, then reload:\n")
	b.WriteString("#   fpath=(~/.zsh/completions $fpath)\n")
	b.WriteString("#   autoload -Uz compinit && compinit\n")
	fmt.Fprintf(&b, "local -a _a2a_cmds _a2a_contract\n")
	fmt.Fprintf(&b, "_a2a_cmds=(%s)\n", zshWords(cmds))
	fmt.Fprintf(&b, "_a2a_contract=(%s)\n", zshWords(subs))
	b.WriteString("if (( CURRENT == 2 )); then\n")
	b.WriteString("    compadd -a _a2a_cmds\n")
	b.WriteString("    return\n")
	b.WriteString("fi\n")
	b.WriteString("if (( CURRENT == 3 )) && [[ \"${words[2]}\" == \"contract\" ]]; then\n")
	b.WriteString("    compadd -a _a2a_contract\n")
	b.WriteString("    return\n")
	b.WriteString("fi\n")
	return b.String()
}

// renderFish emits one `complete` line per verb. Top-level verbs are offered
// only when no subcommand has been typed yet (__fish_use_subcommand); the
// contract sub-verbs only after `contract` (__fish_seen_subcommand_from). `-f`
// disables file completion, which a2a's verbs never take as their first token.
func renderFish(cmds, subs []string) string {
	var b strings.Builder
	b.WriteString("# a2a fish completion. Generated by `a2a completion fish`.\n")
	b.WriteString("# Install: a2a completion fish > ~/.config/fish/completions/a2a.fish\n")
	b.WriteString("complete -c a2a -f\n")
	for _, cmd := range cmds {
		fmt.Fprintf(&b, "complete -c a2a -n __fish_use_subcommand -a %s\n", cmd)
	}
	for _, sub := range subs {
		fmt.Fprintf(&b, "complete -c a2a -n '__fish_seen_subcommand_from contract' -a %s\n", sub)
	}
	return b.String()
}

// zshWords joins verb names for a zsh array literal. The names are a fixed,
// validated vocabulary (buildCommands keys / contract sub-verbs) — plain
// tokens with no shell metacharacters — so they need no quoting; a space
// separator is the zsh array literal form.
func zshWords(names []string) string {
	return strings.Join(names, " ")
}
