#!/usr/bin/env bash
# internal/html/template.html is GENERATED from web/design-source/ and committed
# so the Go build stays hermetic. That combination is exactly the shape that
# silently forks: a fix typed straight into the generated file builds, ships and
# is then erased by the next regeneration — which is precisely what happened
# once (a per-space artifact lookup and an attention-scope comment lived only in
# template.html and were reverted by an unrelated rebuild).
#
# This gate closes it: regenerate into a scratch copy and require the committed
# bytes to match. The build needs the design runtime and the font packages, so a
# local checkout without web/node_modules skips informatively. CI refuses the
# same absence: an automated gate that cannot run must never look green.
#
# --teeth runs the gate's own self-test: mutate the committed file, prove the
# gate goes red, restore it.
#
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
template="$root/internal/html/template.html"
web="$root/web"
script_abs="$root/scripts/dashboard-template-drift.sh"
# Test-only path seam: --teeth exercises dependency presence without moving or
# renaming the checkout's real dependency tree.
node_modules="${A2A_DASHBOARD_NODE_MODULES:-$web/node_modules}"

fail() { printf 'dashboard-template-drift: %s\n' "$1" >&2; exit 1; }

if [ "${1:-}" != "--teeth" ] && [ ! -d "$node_modules" ]; then
  if [ -n "${CI:-}" ]; then
    fail "web/node_modules absent under CI — run 'npm ci' in web/ before dashboard-template-drift"
  fi
  echo "dashboard-template-drift: skipped (web/node_modules absent — run 'npm ci' in web/ to enable)"
  exit 0
fi

if [ "${1:-}" = "--presence-probe" ]; then
  echo "dashboard-template-drift: dependencies present (web/node_modules found)"
  exit 0
fi

regenerate() { # optional $1: teeth-only synthetic generated bytes
  local synthetic="${1:-}"
  if [ -n "$synthetic" ]; then
    cp "$synthetic" "$template"
    return
  fi
  (cd "$web" && npm run --silent build:dashboard >/dev/null)
}

check() { # optional $1: teeth-only synthetic generated bytes
  local synthetic="${1:-}" before after backup
  before="$(git -C "$root" hash-object "$template")" || return 1
  # Restore the bytes that were THERE, not the committed ones. `git checkout --`
  # looks correct and is not: when the working tree legitimately holds a fresh
  # build that has not been committed yet, checkout throws that build away and
  # the next commit ships a stale template. This gate observes; it must never
  # decide what the working tree should contain.
  backup="$(mktemp)" || return 1
  if ! cp "$template" "$backup"; then
    rm -f "$backup"
    return 1
  fi
  if ! regenerate "$synthetic"; then
    cp "$backup" "$template" || true
    rm -f "$backup"
    # 2, not 1: the build did not run, so this gate has NOTHING to say about
    # drift. Both outcomes stay red — a gate that cannot run must never look
    # green — but they are different facts and the caller reports them apart.
    # On 2026-08-20 the build threw ENOENT on Linux (a hardcoded /private/tmp)
    # and this gate announced "template.html differs from a fresh build",
    # sending the reader to diff a file against a build that never happened.
    return 2
  fi
  if ! after="$(git -C "$root" hash-object "$template")"; then
    cp "$backup" "$template" || true
    rm -f "$backup"
    return 1
  fi
  if ! cp "$backup" "$template"; then
    rm -f "$backup"
    return 1
  fi
  rm -f "$backup"
  [ "$before" = "$after" ]
}

if [ "${1:-}" = "--teeth" ]; then
  # Exercise all dependency-presence modes through an isolated path seam. The
  # real web/node_modules directory is never renamed or removed by this test.
  presence_tmp="$(mktemp -d)"
  trap 'rm -rf "$presence_tmp"' EXIT
  missing_modules="$presence_tmp/missing-node-modules"
  present_modules="$presence_tmp/present-node-modules"
  mkdir "$present_modules"
  local_output="$(CI= A2A_DASHBOARD_NODE_MODULES="$missing_modules" "$script_abs" --presence-probe 2>&1)"
  if [[ "$local_output" != *"skipped (web/node_modules absent"* ]]; then
    fail 'teeth failed: local missing dependencies did not produce the informative skip'
  fi
  if ci_output="$(CI=true A2A_DASHBOARD_NODE_MODULES="$missing_modules" "$script_abs" --presence-probe 2>&1)"; then
    fail 'teeth failed: CI missing dependencies exited zero instead of refusing'
  fi
  if [[ "$ci_output" != *"web/node_modules absent"* ]]; then
    fail 'teeth failed: CI missing-dependency refusal did not name web/node_modules absence'
  fi
  present_output="$(A2A_DASHBOARD_NODE_MODULES="$present_modules" "$script_abs" --presence-probe 2>&1)"
  if [[ "$present_output" != *"dependencies present"* ]]; then
    fail 'teeth failed: present dependencies did not continue through the normal path'
  fi
  regen_status=0
  check "$presence_tmp/missing-regenerated-template.html" 2>/dev/null || regen_status=$?
  if [ "$regen_status" -eq 0 ]; then
    fail 'teeth failed: a regeneration error falsely passed as an unchanged template'
  fi
  if [ "$regen_status" -ne 2 ]; then
    fail "teeth failed: a regeneration error must report itself as a failed build (2), not as drift ($regen_status)"
  fi

  # Two proofs: a hand edit to the generated file trips the gate, and a clean
  # tree passes. The original bytes are saved and put back by hand — the
  # self-test must not resort to `git checkout` either, or it would discard an
  # uncommitted build exactly like the bug it exists to prevent.
  teeth_backup="$(mktemp)"
  cp "$template" "$teeth_backup"
  regenerated_template="$presence_tmp/regenerated-template.html"
  cp "$template" "$regenerated_template"
  trap 'cp "$teeth_backup" "$template"; rm -f "$teeth_backup"; rm -rf "$presence_tmp"' EXIT
  printf '\n<!-- teeth: hand edit -->\n' >> "$template"
  if check "$regenerated_template"; then fail 'teeth failed: a hand edit to the generated template did not trip the gate'; fi
  cp "$teeth_backup" "$template"
  if ! check "$regenerated_template"; then fail 'teeth failed: the tracked template does not match its own regeneration'; fi
  echo "dashboard-template-drift: teeth ok (local absence skips, CI absence refuses, regeneration errors and hand edits red; present dependencies and clean bytes pass)"
  exit 0
fi

status=0
check || status=$?
if [ "$status" -eq 2 ]; then
  fail "the regeneration itself failed — the build output above says why.
  This gate cannot judge drift when the build did not run, so it refuses
  rather than reporting a difference it never measured."
elif [ "$status" -ne 0 ]; then
  fail "internal/html/template.html differs from a fresh build of web/design-source/.
  The generated file is not the source of truth. Make the change in
  web/design-source/, then run: (cd web && npm run build:dashboard)"
fi

echo "dashboard-template-drift: template.html matches web/design-source/"
