#!/bin/sh
# Installs an `a2a-dev` wrapper on your PATH that always runs the CURRENT source
# tree — no release download, no manual reinstall after each edit.
#
# It is deliberately NOT called `a2a`. `a2a` must be the RELEASED binary, the
# same one every other participant in your spaces runs: a local build races
# ahead of the pinned releases colleagues use, and a space write made by an
# unreleased binary is a write nobody else can reproduce. Type `a2a-dev` when
# you specifically want unreleased behavior — the divergence should be visible
# at the call site, not ambient in your PATH.
#
# How it stays current without being slow: the wrapper does an incremental
# `go build` ONLY when a Go source (or go.mod/go.sum) is newer than the last
# build, then execs the freshly built binary from YOUR current directory (so
# a2a still resolves config/space from where you invoke it). When nothing
# changed it just execs the cached binary — near-zero overhead. The built
# binary lives in your cache dir, never in the repo.
#
# Usage:  sh scripts/dev-install.sh            # install to ~/.local/bin
#         A2A_BINDIR=/usr/local/bin sh scripts/dev-install.sh
#
# Install the real thing alongside it with scripts/install.sh (or let
# `a2a update` keep it current).
#
# POSIX sh — no bashisms.

set -eu

REPO="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
BINDIR="${A2A_BINDIR:-$HOME/.local/bin}"
WRAPPER="$BINDIR/a2a-dev"
LEGACY="$BINDIR/a2a"

command -v go >/dev/null 2>&1 || { echo "dev-install: Go toolchain not found on PATH — install Go first" >&2; exit 1; }
[ -f "$REPO/cmd/a2a/main.go" ] || { echo "dev-install: $REPO doesn't look like the a2ahub repo (no cmd/a2a/main.go)" >&2; exit 1; }

mkdir -p "$BINDIR"

# Earlier versions of this script installed the wrapper as `a2a`, which shadows
# the released binary. Retire that one — but ONLY if it is provably our own
# generated wrapper (marker line), never a real installed binary.
if [ -f "$LEGACY" ] && grep -q "a2a DEV wrapper — generated by scripts/dev-install.sh" "$LEGACY" 2>/dev/null; then
  rm -f "$LEGACY"
  echo "dev-install: removed the legacy DEV wrapper at $LEGACY (it shadowed the released a2a)."
  echo "             install the real binary with: sh scripts/install.sh"
fi

# Generate the wrapper. REPO is baked in at install time; everything else is
# resolved at run time so the wrapper keeps working as you edit the tree.
cat > "$WRAPPER" <<EOF
#!/bin/sh
# a2a DEV wrapper — generated by scripts/dev-install.sh. Runs the current source
# in the repo below; rebuilds only when sources changed. Re-run dev-install.sh
# to repoint at a different checkout. Do not hand-edit.
# This is `a2a-dev`, NOT `a2a` — `a2a` is the released binary your spaces share.
set -eu
REPO="$REPO"
CACHE="\${XDG_CACHE_HOME:-\$HOME/.cache}/a2a-dev"
BIN="\$CACHE/a2a"
mkdir -p "\$CACHE"
if [ ! -x "\$BIN" ] || [ -n "\$(find "\$REPO/cmd" "\$REPO/internal" "\$REPO/skill" "\$REPO/go.mod" "\$REPO/go.sum" -newer "\$BIN" -print -quit 2>/dev/null)" ]; then
  ( cd "\$REPO" && go build -o "\$BIN" ./cmd/a2a ) 1>&2
fi
exec "\$BIN" "\$@"
EOF
chmod +x "$WRAPPER"

# Warm the cache once so the first real call is instant.
( cd "$REPO" && go build -o "${XDG_CACHE_HOME:-$HOME/.cache}/a2a-dev/a2a" ./cmd/a2a ) || true

echo "a2a-dev wrapper installed -> $WRAPPER"
echo "  it always runs the current source in: $REPO"
echo "  edit the code and just run 'a2a-dev' — it rebuilds itself when needed."
echo "  'a2a' stays the RELEASED binary (scripts/install.sh, then 'a2a update')."

case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo "note: $BINDIR is not on your PATH — add this to your shell rc:"
     echo "      export PATH=\"$BINDIR:\$PATH\"" ;;
esac
