#!/bin/sh
# Installs a `a2a` DEV wrapper on your PATH that always runs the CURRENT source
# tree — your `a2a` everywhere equals your working copy, no release download,
# no manual reinstall after each edit.
#
# How it stays current without being slow: the wrapper does an incremental
# `go build` ONLY when a Go source (or go.mod/go.sum) is newer than the last
# build, then execs the freshly built binary from YOUR current directory (so
# a2a still resolves config/space from where you invoke it). When nothing
# changed it just execs the cached binary — near-zero overhead. The built
# binary lives in your cache dir, never in the repo.
#
# Usage:  sh scripts/dev-install.sh            # install to ~/.local/bin
#         A2A_BINDIR=/usr/local/bin sh scripts/dev-install.sh
#
# POSIX sh — no bashisms.

set -eu

REPO="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
BINDIR="${A2A_BINDIR:-$HOME/.local/bin}"
WRAPPER="$BINDIR/a2a"

command -v go >/dev/null 2>&1 || { echo "dev-install: Go toolchain not found on PATH — install Go first" >&2; exit 1; }
[ -f "$REPO/cmd/a2a/main.go" ] || { echo "dev-install: $REPO doesn't look like the a2ahub repo (no cmd/a2a/main.go)" >&2; exit 1; }

mkdir -p "$BINDIR"

# Generate the wrapper. REPO is baked in at install time; everything else is
# resolved at run time so the wrapper keeps working as you edit the tree.
cat > "$WRAPPER" <<EOF
#!/bin/sh
# a2a DEV wrapper — generated by scripts/dev-install.sh. Runs the current source
# in the repo below; rebuilds only when sources changed. Re-run dev-install.sh
# to repoint at a different checkout. Do not hand-edit.
set -eu
REPO="$REPO"
CACHE="\${XDG_CACHE_HOME:-\$HOME/.cache}/a2a-dev"
BIN="\$CACHE/a2a"
mkdir -p "\$CACHE"
if [ ! -x "\$BIN" ] || [ -n "\$(find "\$REPO/cmd" "\$REPO/internal" "\$REPO/skill" "\$REPO/go.mod" "\$REPO/go.sum" -newer "\$BIN" -print -quit 2>/dev/null)" ]; then
  ( cd "\$REPO" && go build -o "\$BIN" ./cmd/a2a ) 1>&2
fi
exec "\$BIN" "\$@"
EOF
chmod +x "$WRAPPER"

# Warm the cache once so the first real call is instant.
( cd "$REPO" && go build -o "${XDG_CACHE_HOME:-$HOME/.cache}/a2a-dev/a2a" ./cmd/a2a ) || true

echo "a2a dev wrapper installed -> $WRAPPER"
echo "  it always runs the current source in: $REPO"
echo "  edit the code and just run 'a2a' — it rebuilds itself when needed."

case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo "note: $BINDIR is not on your PATH — add this to your shell rc:"
     echo "      export PATH=\"$BINDIR:\$PATH\"" ;;
esac
